language: php

sudo: false

matrix:
    include:
        - php: hhvm
        - php: 5.5
        - php: 5.6
        - php: 7.0
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - pip install codecov

install:
    - composer --prefer-source install

script:
    - composer validate
    - ./vendor/bin/phpcs --standard=PSR2 src
    - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml --verbose

after_success:
    - codecov

notifications:
    slack: monii:XmxGEoN5la6724Zjon4z9FeW
